### ISSUE TITLE
Show Todays Time

### ISSUE THREAD

**Issue by tbrodbeck** [tebeka/toggl#5]
Hi! Great tool! 
I would like to show the amount I have worked of the current day. (Like the today view of the Toggle App itself). Is this possible with this tool?
If yes how can I format it for this purpose?

**Comment by tebeka** [comment]
Thanks. I've been thinking about integrating the [reports API](https://github.com/toggl/toggl_api_docs/blob/master/reports.md). Probably as JSON or CSV output. I'll try over this weekend.

**Comment by tebeka** [comment]
Oh, there's `toggl report <since>` which will show summary for each:
```
$ toggl report 2020-04-01
Project A: 6h3m0s
Project B: 2h0m0s
```

Do you need more functionality?

**Comment by tbrodbeck** [comment]
Oh this is already helpful. Now I know the date formatting :)
So it would be awesome to have those reported values added together with the current "status".
![Screenshot 2020-04-16 at 15 22 06](https://user-images.githubusercontent.com/24418160/79461133-0b826a00-7ff6-11ea-8646-6803cabd0c83.jpg)
Basically I would want the value the toggl app gives me for "Today" in its GUI

**Comment by tebeka** [comment]
Closing due to age.
